### ISSUE TITLE
TYPROTO_LIBRARY 哪里找

### ISSUE THREAD

**Issue by riverai** [typcn/tysocks#1]
你好，本来想试试tysocks，结果cmake到后来提示

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TYPROTO_LIBRARY

它是还没放出来嘛，现在能不能开源了啊。

**Comment by typcn** [comment]
抱歉由于非常忙且没有看到邮件，未能及时回复

库现在已经开源，在 TYPCN/typroto 下

之前没有做过太多测试，可能 bug 比较多。
